### ISSUE TITLE
Feature request - more versatile way to return the resource icon

### ISSUE THREAD

**Issue by gwleuverink** [anaseqal/nova-sidebar-icons#1]
Hi! Thanks a tonne for this package. I love to have the ability to add icons to my resources.

I'd like to propose a change in the way the icon is returned from the resource. If you'd like I can make a pull request. Please let me know what you think.

## Current situation
One thing I do not like is returning the entire svg string in my resource. An example on how this is done now:

``` php
/**
 * The icon of the resource.
 *
 * @var string
 */
public static $icon = '
    <svg class="sidebar-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
        <path fill="var(--sidebar-icon)" d="M4.06 13a8 8 0 0 0 5.18 6.51A18.5 18.5 0 0 1 8.02 13H4.06zm0-2h3.96a18.5 18.5 0 0 1 1.22-6.51A8 8 0 0 0 4.06 11zm15.88 0a8 8 0 0 0-5.18-6.51A18.5 18.5 0 0 1 15.98 11h3.96zm0 2h-3.96a18.5 18.5 0 0 1-1.22 6.51A8 8 0 0 0 19.94 13zm-9.92 0c.16 3.95 1.23 7 1.98 7s1.82-3.05 1.98-7h-3.96zm0-2h3.96c-.16-3.95-1.23-7-1.98-7s-1.82 3.05-1.98 7zM12 22a10 10 0 1 1 0-20 10 10 0 0 1 0 20z"
        />
    </svg>
';
```

## Proposed change
This current approach clutters the resource class quite a bit. I propose to add an additional static function:

``` php
/**
 * The icon of the resource.
 *
 * @return string
 */
public static function icon() {
    return view('nova::svg.icon-building')->render();
}
```

## Benefits
This way is a little more versatile. End users can use any function that returns a string to generate the icon, or just use the icon content like before.

## Impact
The impact in the code is minimal. Only the readme and a couple of lines inside `navigation.blade.php` have to be adjusted.

We can retain the old static icon property to preserve backwards compatibility. This way there is no impact at all. Just a feature bump.

**Comment by anaseqal** [comment]
Thanks, sure any PRs are welcome.

**Comment by anaseqal** [comment]
thank you
